version: "3.8"

x-env-aliases:
  - &DEFAULT_API_ENVS
    NODE_ENV: "development"
    DEBUG: "false"
    ENV: "development"
    DATABASE_HOST: "db"
    DATABASE_NAME: "weather"
    DATABASE_USERNAME: "weather"
    DATABASE_PASSWORD: "weather"
    DATABASE_SYNC: "true"
    REQUEST_LOGGER_ENABLED: "true"
    WEATHER_API_URL: "https://www.metaweather.com/api"
    PORT: "3000"
  - &DEFAULT_POSTGRES_ENVS
    PGDATA: "/var/lib/postgresql/data/pgdata"
    POSTGRES_DB: "weather"
    POSTGRES_PASSWORD: "weather"
    POSTGRES_USER: "weather"

services:
  api:
    build:
      context: weather-app-backend
    environment:
      <<: *DEFAULT_API_ENVS
    ports:
      - 3000:3000
    depends_on:
      - db

  web:
    build:
      context: weather-app-frontend
    volumes:
      - ./weather-app-frontend/.server/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./weather-app-frontend/.server/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - api

  db:
    image: "postgres:11.7"
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    restart: always
    environment:
      <<: *DEFAULT_POSTGRES_ENVS

volumes:
  db_data: {}
