export enum BusinessErrorCode {
  DATABASE_ERROR = 'DATABASE_ERROR',
  ENTITY_CREATION_ERROR = 'ENTITY_CREATION_ERROR',
  ENTITY_DELETE_ERROR = 'ENTITY_DELETE_ERROR',
  ENTITY_NOT_FOUND_ERROR = 'ENTITY_NOT_FOUND_ERROR',
  ENTITY_UPDATE_ERROR = 'ENTITY_UPDATE_ERROR',
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  NO_ACCESS_ERROR = 'NO_ACCESS_ERROR',
  TOO_MANY_REQUESTS_ERROR = 'TOO_MANY_REQUESTS_ERROR',
  UNAUTHORIZED_ERROR = 'UNAUTHORIZED_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  DUPLICATE_ERROR = 'DUPLICATE_ERROR',
}
