export enum BusinessErrorCode {
  DATABASE_ERROR = 'DATABASE_ERROR',
  ENTITY_NOT_FOUND_ERROR = 'ENTITY_NOT_FOUND_ERROR',
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  NO_ACCESS_ERROR = 'NO_ACCESS_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}
