export enum Routes {
  ADMINS = 'admins',
  AUTH = 'auth',
  BOOKINGS = 'bookings',
  CALENDLY = 'calendly',
  CLINIC_ADMINS = 'clinic-admins',
  SUPER_ADMINS = 'super-admins',
  CLINIC_GROUPS = 'clinic-groups',
  CLINICS = 'clinics',
  COSTS = 'costs',
  EXAMPLE = 'example',
  HEALTHCHECK = 'healthcheck',
  HL7 = 'hl7',
  LOCATIONS = 'locations',
  PATIENTS = 'patients',
  PAYMENTS = 'payments',
  RESULTS = 'results',
  STRIPE = 'stripe',
  STRIPE_WEBHOOK = 'stripe/webhook',
}
